FROM node:14.4-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn

ENV PATH="/app/node_modules/.bin:$PATH"

COPY . ./ 
RUN yarn build

CMD ["yarn", "start"]

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
